# Generated by Django 3.2.5 on 2021-07-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20210722_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypicture',
            old_name='user',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='mypicture',
            name='photo',
            field=models.ImageField(default='18035578261.jpg', upload_to='photos'),
        ),
    ]
