# Generated by Django 3.2.5 on 2021-07-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20210723_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
    ]
