# Generated by Django 3.2.5 on 2021-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
