# Generated by Django 3.2.5 on 2021-07-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_delete_segmentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=20)),
                ('top', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
    ]
