# Generated by Django 3.2.5 on 2021-07-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0009_segmentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='segmentation',
        ),
    ]
