# Generated by Django 3.2.5 on 2021-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0011_segmentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField()),
                ('origin', models.CharField(max_length=60)),
                ('processed', models.CharField(max_length=60)),
            ],
        ),
    ]
