# Generated by Django 3.2.5 on 2021-07-28 06:36

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0012_mytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='origin',
            field=models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='tasks'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='processed',
            field=models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='processed'),
        ),
    ]
